[package]
name = "rasterizer"
version = "0.1.0"
authors = ["ifsheldon <maplevantablack@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = "2.0.2"